/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package simulatorecalciogui;

import javax.swing.*;
import static simulatorecalciogui.MainSimulatore.scaleIconKeepRatio;

/**
 *
 * @author tadde
 */
public class InterfacciaFOFA extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfacciaFOFA.class.getName());

    /**
     * Creates new form FOFAGUI
     */
    public InterfacciaFOFA() {
        initComponents();
        m.avvia();
        riempiComboBoxCampionati(cmbCampionatoCasa);
        riempiComboBoxCampionati(cmbCampionatoTrasferta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxPartita = new javax.swing.JTextArea();
        pnlSquadraTrasferta = new javax.swing.JPanel();
        lblTrasferta = new javax.swing.JLabel();
        cmbCampionatoTrasferta = new javax.swing.JComboBox<>();
        cmbSquadraTrasferta = new javax.swing.JComboBox<>();
        lblImmagineTrasferta = new javax.swing.JLabel();
        pnlSquadraCasa = new javax.swing.JPanel();
        lblCasa1 = new javax.swing.JLabel();
        cmbCampionatoCasa = new javax.swing.JComboBox<>();
        cmbSquadraCasa = new javax.swing.JComboBox<>();
        lblImmagineCasa = new javax.swing.JLabel();
        pnlGioca = new javax.swing.JPanel();
        btnGioca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOFA 26");
        setBackground(new java.awt.Color(51, 153, 0));
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("FOFA 26");
        lblTitolo.setToolTipText("");
        lblTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        getContentPane().add(lblTitolo, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(51, 153, 0));

        atxPartita.setColumns(20);
        atxPartita.setRows(5);
        jScrollPane1.setViewportView(atxPartita);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlSquadraTrasferta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTrasferta.setText("Squadra in Trasferta");

        cmbCampionatoTrasferta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCampionatoTrasfertaItemStateChanged(evt);
            }
        });
        cmbCampionatoTrasferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCampionatoTrasfertaActionPerformed(evt);
            }
        });

        cmbSquadraTrasferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSquadraTrasfertaActionPerformed(evt);
            }
        });

        lblImmagineTrasferta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImmagineTrasferta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        javax.swing.GroupLayout pnlSquadraTrasfertaLayout = new javax.swing.GroupLayout(pnlSquadraTrasferta);
        pnlSquadraTrasferta.setLayout(pnlSquadraTrasfertaLayout);
        pnlSquadraTrasfertaLayout.setHorizontalGroup(
            pnlSquadraTrasfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSquadraTrasfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSquadraTrasfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCampionatoTrasferta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSquadraTrasferta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSquadraTrasfertaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTrasferta)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSquadraTrasfertaLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblImmagineTrasferta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlSquadraTrasfertaLayout.setVerticalGroup(
            pnlSquadraTrasfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSquadraTrasfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrasferta)
                .addGap(77, 77, 77)
                .addComponent(cmbCampionatoTrasferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbSquadraTrasferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImmagineTrasferta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSquadraTrasferta, java.awt.BorderLayout.LINE_END);

        pnlSquadraCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCasa1.setText("Squadra in Casa");

        cmbCampionatoCasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCampionatoCasaItemStateChanged(evt);
            }
        });
        cmbCampionatoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCampionatoCasaActionPerformed(evt);
            }
        });

        cmbSquadraCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSquadraCasaActionPerformed(evt);
            }
        });

        lblImmagineCasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImmagineCasa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        javax.swing.GroupLayout pnlSquadraCasaLayout = new javax.swing.GroupLayout(pnlSquadraCasa);
        pnlSquadraCasa.setLayout(pnlSquadraCasaLayout);
        pnlSquadraCasaLayout.setHorizontalGroup(
            pnlSquadraCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSquadraCasaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSquadraCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCampionatoCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSquadraCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSquadraCasaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCasa1)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSquadraCasaLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblImmagineCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        pnlSquadraCasaLayout.setVerticalGroup(
            pnlSquadraCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSquadraCasaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCasa1)
                .addGap(77, 77, 77)
                .addComponent(cmbCampionatoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbSquadraCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblImmagineCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSquadraCasa, java.awt.BorderLayout.LINE_START);

        btnGioca.setText("Gioca");
        btnGioca.setToolTipText("");
        btnGioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGiocaLayout = new javax.swing.GroupLayout(pnlGioca);
        pnlGioca.setLayout(pnlGiocaLayout);
        pnlGiocaLayout.setHorizontalGroup(
            pnlGiocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiocaLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(btnGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        pnlGiocaLayout.setVerticalGroup(
            pnlGiocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGiocaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGioca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlGioca, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCampionatoTrasfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCampionatoTrasfertaActionPerformed
        cmbSquadraTrasferta.removeAllItems();
        riempiComboBoxSquadre(cmbCampionatoTrasferta, cmbSquadraTrasferta);
    }//GEN-LAST:event_cmbCampionatoTrasfertaActionPerformed

    private void cmbCampionatoTrasfertaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCampionatoTrasfertaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCampionatoTrasfertaItemStateChanged

    private void cmbCampionatoCasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCampionatoCasaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCampionatoCasaItemStateChanged

    private void cmbCampionatoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCampionatoCasaActionPerformed
        cmbSquadraCasa.removeAllItems();
        riempiComboBoxSquadre(cmbCampionatoCasa, cmbSquadraCasa);
    }//GEN-LAST:event_cmbCampionatoCasaActionPerformed

    private void cmbSquadraCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSquadraCasaActionPerformed
        riempiImmaginiSquadre(cmbSquadraCasa, lblImmagineCasa);
    }//GEN-LAST:event_cmbSquadraCasaActionPerformed

    private void cmbSquadraTrasfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSquadraTrasfertaActionPerformed
        riempiImmaginiSquadre(cmbSquadraTrasferta, lblImmagineTrasferta);
    }//GEN-LAST:event_cmbSquadraTrasfertaActionPerformed

    private void btnGiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiocaActionPerformed
        for (Squadra s : m.getSquadre()) {
            if (s.getNome().equals(cmbSquadraCasa.getSelectedItem()))
                sCasa = s;
        }
        
        for (Squadra s : m.getSquadre()) {
            if (s.getNome().equals(cmbSquadraTrasferta.getSelectedItem()))
                sTrasferta = s;
        }
            
        pR = new PartitaRunnable(m, sCasa, sTrasferta, atxPartita);
        Thread thread = new Thread(pR);
        thread.start();
    }//GEN-LAST:event_btnGiocaActionPerformed

    public void riempiComboBoxCampionati(JComboBox<String> cmbC) {
        for (String c : m.getCampionati()) {
            cmbC.addItem(c);
        }
    }
    
    public void riempiComboBoxSquadre(JComboBox<String> cmbC, JComboBox<String> cmbS) {
        for (Squadra s : m.getSquadre()) {
            if (s.getCampionato().equals(cmbC.getSelectedItem()))
                cmbS.addItem(s.getNome());
        }
    }
    
    public void riempiImmaginiSquadre(JComboBox<String> cmbS, JLabel l) {
        for (Squadra s : m.getSquadre()) {
            if (s.getNome().equals(cmbS.getSelectedItem())) {
                ImageIcon icon = s.getImmagine();
                if (icon == null || icon.getIconWidth() == -1) {
                    System.out.println("Immagine NON valida per: " + s.getNome());
                } else {
                    if (icon != null) {
                        l.setIcon(scaleIconKeepRatio(icon, 200, 200));
                    }
                    return;
                }
            }
        }
    }
    
    private MainSimulatore m = new MainSimulatore();
    private Squadra sCasa;
    private Squadra sTrasferta;
    private PartitaRunnable pR;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea atxPartita;
    private javax.swing.JButton btnGioca;
    private javax.swing.JComboBox<String> cmbCampionatoCasa;
    private javax.swing.JComboBox<String> cmbCampionatoTrasferta;
    private javax.swing.JComboBox<String> cmbSquadraCasa;
    private javax.swing.JComboBox<String> cmbSquadraTrasferta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCasa1;
    private javax.swing.JLabel lblImmagineCasa;
    private javax.swing.JLabel lblImmagineTrasferta;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JLabel lblTrasferta;
    private javax.swing.JPanel pnlGioca;
    private javax.swing.JPanel pnlSquadraCasa;
    private javax.swing.JPanel pnlSquadraTrasferta;
    // End of variables declaration//GEN-END:variables
}
